version: '3.5'

networks:
  app-tier:
    driver: bridge

services:
  mariadb-master:
    container_name: mariadb-master
    image: bitnami/mariadb:${MARIADB_VERSION}-${MARIADB_OS_VERSION}
    restart: always
    environment:
      - 'TZ=${TIMEZONE}'
      - 'MARIADB_REPLICATION_MODE=master'
      - 'MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER}'
      - 'MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
      - 'MARIADB_USER=${MARIADB_USER}'
      - 'MARIADB_PASSWORD=${MARIADB_PASSWORD}'
      - 'MARIADB_DATABASE=${MARIADB_DATABASE}'
      - 'ALLOW_EMPTY_PASSWORD=no'
    networks:
      - app-tier
    expose:
      - '${MARIADB_PORT}'
    ports: 
      - "${MARIADB_MASTER_PORT}:${MARIADB_PORT}"
    volumes:
      - ./data/mariadb-master:/bitnami/mariadb/data
      - ./logs/mariadb-master:/opt/bitnami/mariadb/logs

  mariadb-slave:
    container_name: mariadb-slave
    image: bitnami/mariadb:${MARIADB_VERSION}-${MARIADB_OS_VERSION}
    restart: always
    environment:
      - 'TZ=${TIMEZONE}'
      - 'MARIADB_REPLICATION_MODE=slave'
      - 'MARIADB_MASTER_HOST=mariadb-master'
      - 'MARIADB_REPLICATION_USER=${MARIADB_REPLICATION_USER}'
      - 'MARIADB_REPLICATION_PASSWORD=${MARIADB_REPLICATION_PASSWORD}'
      - 'MARIADB_MASTER_PORT_NUMBER=${MARIADB_MASTER_PORT}'
      - 'MARIADB_MASTER_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
      - 'ALLOW_EMPTY_PASSWORD=no'
    networks:
      - app-tier
    depends_on: 
      - mariadb-master
    expose:
      - '${MARIADB_PORT}'
    ports: 
      - "${MARIADB_SLAVE_PORT}:${MARIADB_PORT}"
    volumes:
      - ./data/mariadb-slave:/bitnami/mariadb/data
      - ./logs/mariadb-slave:/opt/bitnami/mariadb/logs
